# Generated by Django 4.0.3 on 2022-03-08 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picklistline',
            name='picked_by',
        ),
        migrations.AddField(
            model_name='picklistline',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_lines', to='init_finalapi.inventory'),
            preserve_default=False,
        ),
    ]
