# Generated by Django 4.0.3 on 2022-03-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0003_alter_employee_address_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='enter email here', max_length=55),
        ),
    ]
