# Generated by Django 4.0.3 on 2022-03-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0005_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='pick_list_date',
            field=models.DateField(),
        ),
    ]
