# Generated by Django 4.0.3 on 2022-03-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0006_alter_picklist_pick_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='pick_list_date',
            field=models.DateField(null=True),
        ),
    ]
