# Generated by Django 4.0.3 on 2022-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0007_alter_picklist_pick_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
