# Generated by Django 4.0.3 on 2022-03-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0008_employee_is_active_employee_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
    ]
