# Generated by Django 4.0.3 on 2022-03-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0010_remove_employee_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='init_finalapi.employee'),
        ),
    ]
