# Generated by Django 4.0.3 on 2022-03-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('init_finalapi', '0011_alter_customer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='pick_list_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_lists', to='init_finalapi.picklistline'),
        ),
    ]
